sudo: false

language:
    - cpp

dist:
    - trusty

#env:
#    - BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release"
#    - BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Release"
#    - BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug"
#    - BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug"

#before_install:
#    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#    - sudo apt-get update -qq

matrix:
  include:
#    # 1/ Linux Clang Builds
#    - os: linux
#      compiler: clang
#      addons: &clang60
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
#          packages: ['clang-6.0', 'libc++-6-dev']
#      env: COMPILER='clang++-6.0'

    # 2/ Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: [COMPILER='g++-7', BUILD_FILESYSTEM_PATH_FUNCTION='OFF']

    - os: linux
      compiler: gcc
      addons: &gcc8
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env: [COMPILER='g++-8', BUILD_FILESYSTEM_PATH_FUNCTION='ON']

    # 3/ OSX Clang Builds
    - os: osx
      osx_image: xcode10
      compiler: clang
      env: [BUILD_FILESYSTEM_PATH_FUNCTION='OFF']

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps_"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
        mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        which cmake || brew install cmake
      fi
    - cd ${TRAVIS_BUILD_DIR}

before_script:
    export CXX=${COMPILER}

script:
    - mkdir _build
    - cd _build
    - cmake -DSkyr_BUILD_TESTS=ON -DSkyr_BUILD_DOCS=OFF -DSkyr_BUILD_EXAMPLES=OFF -DSkyr_BUILD_FILESYSTEM_PATH_FUNCTIONS=$BUILD_FILESYSTEM_PATH_FUNCTIONS ..
    - make -j 8
    - make test

after_failure:
    - cat Testing/Temporary/LastTest.log
